name: Update Clash YAML

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        id: run-script
        run: |
          UPDATE_URL=$(python script.py)
          echo "UPDATE_URL=$UPDATE_URL" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add clash.yaml
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update clash.yaml"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/Roywaller/update-clash.git
          fi

      - name: Update README.md
        env:
          UPDATE_URL: ${{ steps.run-script.outputs.UPDATE_URL }}
        run: |
          echo "当前更新链接 $UPDATE_URL" > README.md
          git add README.md
          git commit -m "Update README.md"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/Roywaller/update-clash.git
    
